; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
; Required for TFLite C++ includes
lib_ldf_mode = deep+
; Optimizes execution speed for inference
build_flags = -O3
lib_deps =
    arduino-libraries/Arduino_APDS9960
    https://github.com/tensorflow/tflite-micro-arduino-examples.git

[env:data]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
build_src_filter = +<data_collection.cpp>
lib_deps =
    arduino-libraries/Arduino_APDS9960
; (Kept lightweight: TFLite dependencies omitted here for faster build times during data collection)

[env:inference]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
build_src_filter = +<inference.cpp>
; Required for TFLite C++ includes
lib_ldf_mode = deep+
; Optimizes execution speed for inference
build_flags = -O3
lib_deps =
    arduino-libraries/Arduino_APDS9960
    https://github.com/tensorflow/tflite-micro-arduino-examples.git


